spring:
  application:
    name: data-jpa

  datasource:
    url: jdbc:mysql://localhost:3306/example
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
