spring:
  application:
  name: data-jpa

  datasource:
    url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=utf8mb4
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
    database-platform: org.hibernate.dialect.MySQLDialect
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        connection:
          useUnicode: true
          characterEncoding: utf8
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
logging:
  level:
    org:
      hibernate.SQL: DEBUG
#        resource:
#          transaction: DEBUG
      springframework:
        orm:
          jpa:
            JpaTransactionManager: DEBUG
        jdbc:
          datasource:
            DataSourceTransactionManager: DEBUG
        transaction:
          interceptor: TRACE
