---
spring:
  config:
    activate:
      on-profile: local
db:
  url: '{cipher}encryptedData'
  username: '{cipher}encryptedUsername'
  password: '{cipher}encryptedPassword'
  somethingKey: '{cipher}encryptedSomethingKey'
  somethingKey2: '{cipher}encryptedSomethingKey2'
