POST localhost:8080/token
Authorization: Basic dXNlcjE6MTIzNA==

###
GET localhost:8080/user
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidXNlcjEiLCJleHAiOjE3MjU5NTEwNTcsImlhdCI6MTcyNTk1MDQ1Nywic2NvcGUiOiIgIn0.GsMwHHSMencyrqXTPEEOKK-oyc4hE_1VJSp00p3NG34
