POST localhost:8080/token
Authorization: Basic dXNlcjI6MTIzNA==
### dXNlcjI6MTIzNA==
###
GET localhost:8080/
Content-Type: text/html
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidXNlcjIiLCJleHAiOjE3MjU5NTQ4NzQsImlhdCI6MTcyNTk1NDI3NCwic2NvcGUiOiJST0xFX0FETUlOIn0.IRemJHE8qDjBeuo9xh2VPzddVfqVSjD-hGhctbaaFp0







