spring:
  application:
    name: spring-cloud
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chanho0912/spring-config-sample
          default-label: main
          try-master-branch: false
        encrypt:
          enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=utf8mb4
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
  security:
    user:
      name: sa
      password: 1234
