spring:
  application:
    name: spring-cloud
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chanho0912/blog-example.git
          default-label: main
          try-master-branch: false
          repos:
            spring-config-client:
              pattern: spring-config-client
              uri: https://github.com/chanho0912/blog-example.git
              search-paths: spring-cloud/config-server/config-yaml
        encrypt:
          enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=utf8mb4
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
  security:
    user:
      name: sa
      password: 1234
