spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=utf8mb4
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8

server:
  port: 8080

## MyBatis
mybatis:
  type-aliases-package: com.noah.simpleitemservice.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.noah.simpleitemservice.repository.mybatis: trace
