spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=utf8mb4
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate.use_sql_comments: true
      hibernate.type: trace

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
