spring:
  profiles:
    active: local
  application:
    name: spring-config-client
  config:
    import: optional:configserver:http://localhost:8080
  cloud:
    config:
      username: user1
      password: 1234

server:
  port: 8081

system:
  url: ${db.url}
  username: ${db.username}
  password: ${db.password}

#logging:
#  level:
#    org:
#      springframework: DEBUG